### ISSUE TITLE
2D arrays as inputs to a method generate interfaces with incorrect asterisks in their array definitions

### ISSUE THREAD

**Issue by FatSwords** [StefH/ProxyInterfaceSourceGenerator#54] opened 2023-02-20 17:19 UTC
I have a class I want to create a proxy interface/proxy for.  It has a method as below:

`
public void DoStuff(double input, [Out] double[,] output)
        {
                //Do some stuff
        }
`

Upon running the code generation, I get an interface which looks like this:

`
void DoStuff(double input, double[*,*] output);
`

which does not compile, and is missing the out keyword.  It might be the combination of the out keyword and the 2D array which is causing the issue - not sure yet.

**Comment by StefH** [comment] 2023-02-21 07:12
@FatSwords 

The `out` should work fine : see https://github.com/StefH/ProxyInterfaceSourceGenerator/blob/390093d0076d7541f7363df3227d71e7c0c2cdaf/src-examples/ProxyInterfaceConsumerViaNuGet/PersonProxy2.cs#L61

Did you try your code as:
``` c#
public void DoStuff(double input, out double[,] output) { //Do some stuff }
```

BTW: It could be that the problem is 2D array, I'll check this.

**Comment by StefH** [comment] 2023-02-21 18:09
https://github.com/StefH/ProxyInterfaceSourceGenerator/pull/55

**Comment by StefH** [comment] 2023-02-21 18:11
@FatSwords 
It's fixed.
A new version will be released shortly.

**Closed by StefH** 2023-02-21 18:11 UTC
Labels: bug

**Comment by FatSwords** [comment] 2023-02-23 13:32
Awesome - just got that running and it works a treat - thank you!
