### ISSUE TITLE
Invalid code is generated for some locales (e.g. sv-ES)

### ISSUE THREAD

**Issue by rogeralsing** [StefH/ProxyInterfaceSourceGenerator#40] opened 2022-12-12 10:33 UTC
How to reproduce:

New empty console app:

Add following Nugets:
* Akka.Remote
* ProxyInterfaceGenerator

In Program.cs:

```csharp
using Akka.Actor;

[ProxyInterfaceGenerator.Proxy(typeof(LocalActorRefProvider))]
public partial interface ILocalActorRefProvider
{
}
```

This results in the following build errors:

<img width="748" alt="Skärmavbild 2022-12-12 kl  11 32 37" src="https://user-images.githubusercontent.com/647031/207023601-1bf508ac-2cce-495e-89a9-18b0af9b1463.png">

**Comment by StefH** [comment] 2022-12-12 21:05
@rogeralsing 
When I use your example code, it works just fine?

Can you take a look at this example : https://github.com/StefH/ProxyInterfaceSourceGenerator/tree/akka/src-examples/ProxyInterfaceConsumerForAkka

**Comment by rogeralsing** [comment] 2022-12-12 22:28
I get the same error
<img width="386" alt="Skärmavbild 2022-12-12 kl  23 24 35" src="https://user-images.githubusercontent.com/647031/207168236-f1a1b7fb-47e5-4db3-b7ab-736f7043fb92.png">

I do have a hunch on what this is.
https://github.com/dotnet/runtime/issues/26778

The dash there is `−` which is not the same as `-` minus (see how the first is wider).

**Comment by StefH** [comment] 2022-12-13 06:43
@rogeralsing 
Can you please go to "dependencies --> analyzers --> ProxyInterfaceSourceGenerator" and copy-paste the generated C# file which causes compile errors?

![image](https://user-images.githubusercontent.com/249938/207245087-1bc766bf-2063-4758-98b9-2b337c71b40c.png)

**Comment by rogeralsing** [comment] 2022-12-13 07:06
The generated code is full of these invalid variable names:

<img width="1218" alt="Skärmavbild 2022-12-13 kl  08 05 06" src="https://user-images.githubusercontent.com/647031/207249024-5781eb20-87be-4f01-ac4b-454f4b95aad6.png">

```
        public int DefaultValue(int x = 100)
        {
            int x_ = x;
            var result_−378509684 = _Instance.DefaultValue(x_);
            return result_−378509684;
        }
```

**Comment by StefH** [comment] 2022-12-13 07:08
I see. Thank you very much for your analysis. I know the cause from this error, I'll keep you up to date here on the progress.

**Comment by StefH** [comment] 2022-12-13 11:29
@rogeralsing 
Issue is related to this line: https://github.com/StefH/ProxyInterfaceSourceGenerator/blob/main/src/ProxyInterfaceSourceGenerator/Extensions/StringExtensions.cs#L26 , I'll fix this.

Some questions:
- Do you use Rider or a different visual studio?
- What is your locale / country on your PC?

**Comment by rogeralsing** [comment] 2022-12-13 13:18
Swedish locale.
Mac
Rider

I believe the issue at hand here is Mac (Or even *Nix?) that the minus sign is a different character.
I'm not sure if this is related to specifically Swedish locale.
That is actually the locale used in this bugreport:
https://github.com/dotnet/runtime/issues/26778#issuecomment-404236462

**Comment by StefH** [comment] 2022-12-13 15:42
https://github.com/StefH/ProxyInterfaceSourceGenerator/pull/41

**Comment by StefH** [comment] 2022-12-13 15:44
@rogeralsing 
Code is fixed, a new NuGet will be released shortly.

**Closed by StefH** 2022-12-13 15:44 UTC
Labels: bug

**Comment by rogeralsing** [comment] 2022-12-13 15:55
Awesome! thanks
